package dev.giovannidrago.photoatlas.studio.ui.theme

import androidx.compose.ui.graphics.Color

// Photo Atlas teal seed (same identity as the Flutter app).
val TealSeed = Color(0xFF00696B)

// Light scheme
val LightPrimary = Color(0xFF00696B)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFF9CF1F2)
val LightOnPrimaryContainer = Color(0xFF002021)
val LightSecondary = Color(0xFF4A6363)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFCCE8E8)
val LightOnSecondaryContainer = Color(0xFF051F1F)
val LightTertiary = Color(0xFF4B607C)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFD3E4FF)
val LightOnTertiaryContainer = Color(0xFF041C35)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF410002)
val LightBackground = Color(0xFFF5FBFB)
val LightOnBackground = Color(0xFF161D1D)
val LightSurface = Color(0xFFF5FBFB)
val LightOnSurface = Color(0xFF161D1D)
val LightSurfaceVariant = Color(0xFFDAE5E4)
val LightOnSurfaceVariant = Color(0xFF3F4949)
val LightOutline = Color(0xFF6F7979)
val LightOutlineVariant = Color(0xFFBEC9C8)
val LightSurfaceContainerLowest = Color(0xFFFFFFFF)
val LightSurfaceContainerLow = Color(0xFFEFF5F4)
val LightSurfaceContainer = Color(0xFFE9EFEE)
val LightSurfaceContainerHigh = Color(0xFFE3E9E9)
val LightSurfaceContainerHighest = Color(0xFFDDE4E3)
val LightInverseSurface = Color(0xFF2B3232)
val LightInverseOnSurface = Color(0xFFECF2F1)
val LightInversePrimary = Color(0xFF80D4D5)

// Dark scheme
val DarkPrimary = Color(0xFF80D4D5)
val DarkOnPrimary = Color(0xFF003737)
val DarkPrimaryContainer = Color(0xFF004F50)
val DarkOnPrimaryContainer = Color(0xFF9CF1F2)
val DarkSecondary = Color(0xFFB0CCCC)
val DarkOnSecondary = Color(0xFF1B3534)
val DarkSecondaryContainer = Color(0xFF324B4B)
val DarkOnSecondaryContainer = Color(0xFFCCE8E8)
val DarkTertiary = Color(0xFFB3C8E8)
val DarkOnTertiary = Color(0xFF1C314B)
val DarkTertiaryContainer = Color(0xFF334863)
val DarkOnTertiaryContainer = Color(0xFFD3E4FF)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
val DarkBackground = Color(0xFF0E1515)
val DarkOnBackground = Color(0xFFDDE4E3)
val DarkSurface = Color(0xFF0E1515)
val DarkOnSurface = Color(0xFFDDE4E3)
val DarkSurfaceVariant = Color(0xFF3F4949)
val DarkOnSurfaceVariant = Color(0xFFBEC9C8)
val DarkOutline = Color(0xFF899393)
val DarkOutlineVariant = Color(0xFF3F4949)
val DarkSurfaceContainerLowest = Color(0xFF090F0F)
val DarkSurfaceContainerLow = Color(0xFF161D1D)
val DarkSurfaceContainer = Color(0xFF1A2121)
val DarkSurfaceContainerHigh = Color(0xFF252B2B)
val DarkSurfaceContainerHighest = Color(0xFF303737)
val DarkInverseSurface = Color(0xFFDDE4E3)
val DarkInverseOnSurface = Color(0xFF2B3232)
val DarkInversePrimary = Color(0xFF00696B)
